In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
a[0]

1

In [7]:
a[1]=4

In [8]:
a

array([1, 4, 3])

In [9]:
b = np.array([[1,2,3],[4,5,6]])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.shape

(2, 3)

In [12]:
b[0,:]

array([1, 2, 3])

In [13]:
b[1,:]

array([4, 5, 6])

In [14]:
b[1]

array([4, 5, 6])

In [15]:
b[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a = np.zeros((2,2))

In [17]:
a

array([[ 0.,  0.],
       [ 0.,  0.]])

In [18]:
a = np.ones((1,3))

In [19]:
a

array([[ 1.,  1.,  1.]])

In [20]:
a = np.full((3,3),4)

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full((3, 3), 4) will return an array of dtype('int32')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [21]:
a

array([[ 4.,  4.,  4.],
       [ 4.,  4.,  4.],
       [ 4.,  4.,  4.]])

In [22]:
a = np.eye(2)

In [23]:
a

array([[ 1.,  0.],
       [ 0.,  1.]])

In [25]:
a = np.random.random((3,2))
a

array([[ 0.65884238,  0.58999416],
       [ 0.99299012,  0.83907723],
       [ 0.32901505,  0.61928232]])

In [26]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6]])

In [27]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6]])

In [28]:
a[:2,:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [29]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [30]:
a.shape

(3, 2)

In [31]:
np.arange(4)

array([0, 1, 2, 3])

In [32]:
(a>2)

array([[False, False],
       [ True,  True],
       [ True,  True]], dtype=bool)

In [33]:
a[a>2]

array([3, 4, 5, 6])

In [34]:
a.dtype

dtype('int32')

In [35]:
np.array([1.0, 2.0]).dtype

dtype('float64')

In [36]:
np.array([1, 2], dtype=np.int64).dtype

dtype('int64')

In [37]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [38]:
x+y

array([[  6.,   8.],
       [ 10.,  12.]])

In [39]:
x-y

array([[-4., -4.],
       [-4., -4.]])

In [40]:
x*y

array([[  5.,  12.],
       [ 21.,  32.]])

In [41]:
x/y

array([[ 0.2       ,  0.33333333],
       [ 0.42857143,  0.5       ]])

In [42]:
np.sqrt(x)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [43]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [44]:
v.dot(w)

219

In [45]:
v.dot(x)

array([39, 58])

In [46]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [47]:
x.dot(v)    

array([29, 67])

In [48]:
x = np.array([[1,2],[3,4]])

In [49]:
np.sum(x)

10

In [50]:
np.sum(x,axis=1)

array([3, 7])

In [51]:
np.sum(x,axis=0)

array([4, 6])

In [52]:
x.T

array([[1, 3],
       [2, 4]])

In [53]:
x

array([[1, 2],
       [3, 4]])

In [54]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

In [55]:
y = np.empty_like(x)

In [56]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [57]:
y

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [58]:
for i in range(4):
    y[i:] = x[i:]+v

In [59]:
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [60]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))
print(vv) 
y = x + vv
print(y)  

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
